version: '3.7'
services:
  redis:
    image: redis:latest
    command: redis-server --requirepass your_redis_password --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - "app-network"
  redisinsight:
    image: redislabs/redisinsight:latest
    environment:
      - REDISINSIGHT_HOSTS=redis:6379
      - REDISINSIGHT_PASSWORD=your_redisinsight_password
    ports:
      - 8001:8001
    networks:
      - "app-network"
    depends_on:
      - redis

volumes:
  redis_data:

networks:
  app-network:
    external: true